project_name: spectrogram
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
release:
  disable: true
